### PR TITLE
Added Greenlight Link as Button

### PR DESCRIPTION
**Pull request by Scarwolf**

### CODE REVIEW

**Comment by Jaex** [comment]
I was just going to add it but you become faster than me :P

**Comment by Jaex** [comment]
But I didn't liked how that button look there, if you don't mind I will move it to top too.

**Comment by Scarwolf** [comment]
No Problem. I spent 20 minutes thinking about how I could integrate it so it looks good :P

**Comment by Jaex** [comment]
I thinked alot too and couldn't decide where to put therefore was not added yet :P

**Comment by Scarwolf** [comment]
Alright. Sent you a message using the contact form btw regarding translations. WOuld be nice if you could take a look at it :)

**Comment by Jaex** [comment]
I already replied to it long time ago.

**Comment by Scarwolf** [comment]
Damn, you're fast. Thank you.

**Comment by Jaex** [comment]
I moved Greenlight button top and it look better like this.

**Comment by Scarwolf** [comment]
Maybe highlight it green? I assume that People won't notice it like this.

**Pull request merged**
